kotlin.code.style = official
org.gradle.jvmargs = -Xmx1G
org.gradle.warning.mode = all
loom.platform = neoforge
# Check these on https://fabricmc.net/versions.html
minecraftVersion=26.2
loaderVersion = 26.2.0.8-beta
# ModDevGradle
mdgVersion = 2.0.140

# Mod Properties
modVersion = 0.3.3
mavenGroup = fzzyhmstrs
archivesBaseName = particle_core
# Kotlin
systemProp.kotlinVersion = 2.3.10
kotlinForForgeVersion = 6.2.0
# Dependencies
guavaVersion = 32.0.0-jre
fzzyConfigVersion = 0.7.6
cmVersion = 0.6.4
# uploads
mcVersions = 26.2
uploadDebugMode = false
releaseType = release
modrinthSlugName = particle-core