kotlin.code.style = official
org.gradle.jvmargs = -Xmx2G
org.gradle.warning.mode = all
# Check these on https://fabricmc.net/versions.html
minecraftVersion=26.1
loaderVersion =0.19.2
# Fabric API
fabricVersion=0.145.1+26.1
loomVersion = 1.16-SNAPSHOT
# Mod Properties
modVersion = 0.3.2
mavenGroup = fzzyhmstrs
archivesBaseName = particle_core
# Kotlin
systemProp.kotlinVersion = 2.3.10
fabricKotlinVersion = 1.13.9+kotlin.2.3.10
# Dependencies
guavaVersion = 32.0.0-jre
fzzyConfigVersion = 0.7.6
cmVersion = 0.5.1
# uploads
mcVersions = 1.21.11
uploadDebugMode = false
releaseType = release
modrinthSlugName = particle-core