kotlin.code.style = official
org.gradle.jvmargs = -Xmx2G
org.gradle.warning.mode = all
# Check these on https://fabricmc.net/versions.html
minecraftVersion=26.2
loaderVersion =0.19.3
# Fabric API
fabricVersion=0.153.0+26.2
loomVersion = 1.17-SNAPSHOT
# Mod Properties
modVersion = 0.3.2
mavenGroup = fzzyhmstrs
archivesBaseName = particle_core
# Kotlin
systemProp.kotlinVersion = 2.4.0
fabricKotlinVersion = 1.13.12+kotlin.2.4.0
# Dependencies
guavaVersion = 33.6.0-jre
fzzyConfigVersion = 0.7.6
cmVersion = 0.6.4
# uploads
mcVersions = 26.1,26.1.1,26.1.2
uploadDebugMode = false
releaseType = release
modrinthSlugName = particle-core